[package]
name = "ratto-entry"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
ratto-kernel = { path = "../ratto-kernel" }
ratto-qemu = { path = "../ratto-qemu", optional = true }

[features]
qemu = ["ratto-qemu"]
